FROM oven/bun:1.3-alpine

WORKDIR /app

COPY backend/package.json backend/bun.lock* ./
RUN bun install --frozen-lockfile

COPY backend/ .
COPY shared/ /shared

CMD ["sh", "-c", "bun run src/db/migrate.ts && bun run src/index.ts"]

EXPOSE 5001
