ALTER TABLE users ADD COLUMN IF NOT EXISTS institution_name VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS institution_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
